# Generated by Django 2.2.4 on 2019-08-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_chats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='chats',
            new_name='tickets',
        ),
    ]
